// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBoq3CMaem35ip8xaO0KoYeY8tlVI-z2nk',
    appId: '1:1042792738341:web:29d233731575b7cca319cc',
    messagingSenderId: '1042792738341',
    projectId: 'app-secondchance',
    authDomain: 'app-secondchance.firebaseapp.com',
    storageBucket: 'app-secondchance.firebasestorage.app',
    measurementId: 'G-XMC1F1KP44',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCNxrggOHNewaQl9KUp9ek5Fdbcq7f8V94',
    appId: '1:1042792738341:android:36481e19ad76d1a8a319cc',
    messagingSenderId: '1042792738341',
    projectId: 'app-secondchance',
    storageBucket: 'app-secondchance.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD-D2dLQLfuIV4QeME56R0ozSh8ayDlceg',
    appId: '1:1042792738341:ios:6961c8b6c8f42b7ca319cc',
    messagingSenderId: '1042792738341',
    projectId: 'app-secondchance',
    storageBucket: 'app-secondchance.firebasestorage.app',
    iosBundleId: 'com.example.appDoCu',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD-D2dLQLfuIV4QeME56R0ozSh8ayDlceg',
    appId: '1:1042792738341:ios:6961c8b6c8f42b7ca319cc',
    messagingSenderId: '1042792738341',
    projectId: 'app-secondchance',
    storageBucket: 'app-secondchance.firebasestorage.app',
    iosBundleId: 'com.example.appDoCu',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBoq3CMaem35ip8xaO0KoYeY8tlVI-z2nk',
    appId: '1:1042792738341:web:f2cf90895adfa19da319cc',
    messagingSenderId: '1042792738341',
    projectId: 'app-secondchance',
    authDomain: 'app-secondchance.firebaseapp.com',
    storageBucket: 'app-secondchance.firebasestorage.app',
    measurementId: 'G-SYGTMCQ0JQ',
  );
}
